# Portainer CE Configuration
# Docker management UI

var_cpu="2"
var_ram="1024"
var_disk="8"
var_os="debian"
var_version="12"

DOCKER_IMAGE="portainer/portainer-ce:latest"
DOCKER_PORTS="9443:9443,8000:8000"
DOCKER_VOLUMES="/var/run/docker.sock:/var/run/docker.sock,/srv/portainer:/data"
DOCKER_RESTART="unless-stopped"
